[package]
name = "ephemeris-cmd"
version = "0.2.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[[bin]]
name = "ephemeris"
path = "src/main.rs"


[dependencies]
chrono = {version = "^0.4.19", features=["serde"]}
chrono-tz = "^0.5.3"
clap = {version = "3.0.0-beta.2", features = [ "suggestions", "color" ]}
prettytable-rs = "^0.8"
rustyline = "8.2.0"
ephemeris = {path = "../ephemeris-lib"}
